### ISSUE TITLE
部署过程中deploy处配置有歧义

### ISSUE THREAD

**Issue by floatval** [limedroid/HexoLearning#11]
文中deploy处的配置：
```
deploy:
  type: git
  repo: <repository url>
  branch: [branch]
```
repo后的尖括号，和branch后的方括号，如果在其中进行添加内容的话，会造成 ```hexo d``` 无法更新
**版本**
```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Linux 4.17.4-1-ARCH linux x64
http_parser: 2.8.1
node: 10.6.0
v8: 6.7.288.46-node.13
uv: 1.21.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```
